
# Loads default set of integrations. Do not remove.
#default_config:
my:

# Load frontend themes from the themes folder
frontend:
  themes: !include_dir_merge_named themes

automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml
http:
  use_x_forwarded_for: true
  trusted_proxies:
    - 127.0.0.1 # Add the IP address of the proxy server
    - 192.168.1.0/24
      #- 192.168.1.202
      #- 192.168.1.203
#homeassistant:
#auth_providers:
#- type: trusted_networks
#trusted_networks:
#- 192.168.1.0/24
#- fd00::/8
#- 127.0.0.1
#- ::1
  #allow_bypass_login: true
